name: expand_widget
description: Ability to easily expand and retract a widget collection or text
version: 1.0.0+1
homepage: https://github.com/jesusrp98/expand_widget

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
